[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[functions]]
  name = "postNewTokens"
  schedule = "*/1 * * * *"
